etat/urls.py
from django.urls import path
from . import views

app_name = 'etat'
urlpatterns = [
    path('', views.etat, name='etat'),

    # Url des bouttons Membre
    path('fiche-identification', views.fiche_identification, name='fiche_identification'),
    path('retour-etat/<str:id>', views.retour_etat, name='retour_etat'),
    path('liste-badge', views.liste_badge, name='liste_badge'),
    path('total-enfants', views.total_enfants, name='total_enfants'),
    path('nouvelle-naissance', views.nouvelle_naissance, name='nouvelle_naissance'),
    path('total-deces', views.total_deces, name='total_deces'),
    path('total-deces-enfant', views.total_deces_enfant, name='total_deces_enfant'),
    path('total-accident', views.total_accident, name='total_accident'),
    path('total-accident-enfant', views.total_accident_enfant, name='total_accident_enfant'),

    # Url des bouttons Coopérative et groupement
    path('liste-secteur-activite', views.liste_secteur_activite, name='liste_secteur_activite'),
    path('liste-membre', views.liste_membre, name='liste_membre'),

]

localisation/urls.py
from django.urls import path
from . import views

app_name = 'localisation'
urlpatterns = [
    path('', views.localisation, name = 'localisation'),

    # Url du district
    path('ajouter-district', views.ajouter_district, name = 'ajouter_district'),
    path('modifier-district', views.modifier_district, name = 'modifier_district'),
    path('supprimer-district/<str:id>', views.supprimer_district, name = 'supprimer_district'),

    # Url de la région
    path('ajouter-region', views.ajouter_region, name = 'ajouter_region'),
    path('modifier-region', views.modifier_region, name = 'modifier_region'),
    path('supprimer-region/<str:id>', views.supprimer_region, name = 'supprimer_region'),
    path('details-region', views.details_region, name = 'details_region'),

    # Url de la département
    path('ajouter-departement', views.ajouter_departement, name = 'ajouter_departement'),
    path('modifier-departement', views.modifier_departement, name = 'modifier_departement'),
    path('supprimer-departement/<str:id>', views.supprimer_departement, name = 'supprimer_departement'),

    # Url de la ville
    path('ajouter-ville', views.ajouter_ville, name = 'ajouter_ville'),
    path('modifier-ville', views.modifier_ville, name = 'modifier_ville'),
    path('supprimer-ville/<str:id>', views.supprimer_ville, name = 'supprimer_ville'),
    path('details-departement', views.details_departement, name = 'details_departement'),

    # Url de la Commune
    path('ajouter-commune', views.ajouter_commune, name = 'ajouter_commune'),
    path('modifier-commune', views.modifier_commune, name = 'modifier_commune'),
    path('supprimer-commune/<str:id>', views.supprimer_commune, name = 'supprimer_commune'),
    path('details-ville', views.details_ville, name = 'details_ville'),

    # Url du Quartier
    path('ajouter-quartier', views.ajouter_quartier, name = 'ajouter_quartier'),
    path('modifier-quartier', views.modifier_quartier, name = 'modifier_quartier'),
    path('supprimer-quartier/<str:id>', views.supprimer_quartier, name = 'supprimer_quartier'),
    path('details-commune', views.details_commune, name = 'details_commune'),

    # Url du Marché
    path('ajouter-marche', views.ajouter_marche, name='ajouter_marche'),
    path('modifier-marche', views.modifier_marche, name='modifier_marche'),
    path('supprimer-marche/<str:id>', views.supprimer_marche, name='supprimer_marche'),
    path('details-quartier', views.details_quartier, name='details_quartier'),
    path('details-marche', views.details_marche, name='details_marche'),
]

projet/urls.py
"""projet URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler400, handler403
from django.conf.urls.static import static

# Configuration des erreurs
handler404 = 'utilisateur.views.handler404'
handler500 = 'utilisateur.views.handler500'
handler400 = 'utilisateur.views.handler400'
handler403 = 'utilisateur.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('localisation/', include('localisation.urls')),
    path('etatcivil/', include('etatcivil.urls')),
    path('vieprofessionnelle/', include('vieprofessionnelle.urls')),
    path('presentation/', include('presentation.urls')),
    path('etat/', include('etat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

localisation/models.py
from django.db import models
from projet.models import *

# Liste des méthodes Globales du projet --------
def nombre_membre_par_ville(quartier=None, ville=None):
    """
        Cette méthode permet d'obtenir le nombre de membres par ville
        Ex: quartier = objet quartier ou ville = objet ville
            la valeur de retour = 0 s'il n'y a aucun membre dans cette ville
            la valeur de retour = 12 s'il y a des membres dans cette ville
    """
    if ville:
        return Quartier.objects.filter(membre__quartier__commune__ville__code=ville.code).count()
    else:
        return Quartier.objects.filter(membre__quartier__commune__ville__code=quartier.commune.ville.code).count()

#--------------------------------------------------


class District(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="District", unique=True)

    def __str__(self):
        return self.libelle

class Region(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Region", unique=True)
    district = models.ForeignKey(District,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.libelle

class Departement(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Departement", unique=True)
    region = models.ForeignKey(Region,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.libelle

class Ville(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Ville", unique=True)
    departement = models.ForeignKey(Departement,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.libelle

class Commune(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Commune", unique=True)
    ville = models.ForeignKey(Ville,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.libelle

class Quartier(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Quartier", unique=True)
    commune = models.ForeignKey(Commune, on_delete=models.SET_NULL, null=True)

    # Les methodes
    def __str__(self):
        return self.libelle

    def get_nombre_membre_par_ville(self):
        return nombre_membre_par_ville(quartier=self)

class Marche(models.Model):
    code = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Marché", unique=True)
    quartier = models.ForeignKey(Quartier, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.libelle

localisation/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse

# Les constatntes et les variables globales
_active_onglet = "" # Variable globale pour l'activation des onglets

@login_required
@permission_required('vieprofessionnelle.view_membre', raise_exception=True)
def localisation(request):

    districts = District.objects.all().order_by("libelle")
    regions = Region.objects.all().order_by("libelle")
    departements = Departement.objects.all().order_by("libelle")
    villes = Ville.objects.all().order_by("libelle")
    communes = Commune.objects.all().order_by("libelle")
    quartiers = Quartier.objects.all().order_by("libelle")
    marches = Marche.objects.all().order_by("libelle")

    # Initialisation de l'affichage de l'onglet active
    active_district = ['','false','']
    active_region = ['','false','']
    active_departement = ['','false','']
    active_ville = ['','false','']
    active_commune = ['','false','']
    active_quartier = ['','false','']
    active_marche = ['','false','']

    if _active_onglet == "district":
        active_district =  ['active', 'true', 'show active']
    elif _active_onglet == "region":
        active_region = ['active', 'true', 'show active']
    elif _active_onglet == "departement":
        active_departement = ['active', 'true', 'show active']
    elif _active_onglet == "ville":
        active_ville = ['active', 'true', 'show active']
    elif _active_onglet == "commune":
        active_commune = ['active', 'true', 'show active']
    elif _active_onglet == "quartier":
        active_quartier = ['active', 'true', 'show active']
    elif _active_onglet == "marche":
        active_marche = ['active', 'true', 'show active']
    else:
        # Affichage par défaut
        active_district =  ['active', 'true', 'show active']


    context = {
        "titre" : "Localisation",
        "districts" : districts,
        "regions" : regions,
        "departements" : departements,
        "villes": villes,
        "communes": communes,
        "quartiers": quartiers,
        "marches": marches,

        "active_district": active_district,
        "active_region": active_region,
        "active_departement": active_departement,
        "active_ville": active_ville,
        "active_commune": active_commune,
        "active_quartier": active_quartier,
        "active_marche": active_marche,

    }

    return render(request, "localisation/localisation.html", context)

# Gestion du district -----------------------------------------------

@login_required
@permission_required('localisation.add_district', raise_exception=True)
def ajouter_district(request):

    global _active_onglet
    _active_onglet = "district"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        code = request.POST.get("code", None)
        libelle = request.POST.get("libelle", None)

        if code and libelle:
            # On vérifie si le code et le libelle existe
            # On format les chaine
            libelle = libelle.capitalize()

            try:
                district = District.objects.get(code = code)
                messages.error(request, f"Ce code :[{code}] existe déjà.")
                return HttpResponseRedirect(reverse('localisation:localisation'))

            except District.DoesNotExist:
                try:
                    district = District.objects.get(libelle = libelle)
                    messages.error(request, f"Ce libellé :[{libelle}] existe déjà.")
                    return HttpResponseRedirect(reverse('localisation:localisation'))
                except District.DoesNotExist:
                    pass
            #----
            district = District()
            district.code = code
            district.libelle = libelle
            district.save()

            messages.success(request,"Enregistrement réussi.")

            return HttpResponseRedirect(reverse('localisation:localisation'))
    else:
        return HttpResponseRedirect(reverse('localisation:localisation'))

@login_required
@permission_required('localisation.change_district', raise_exception=True)
def modifier_district(request):

    global _active_onglet
    _active_onglet = "district"  # On initialise la variable

    if request.method == "POST":

        try:
            district = District.objects.get(id=request.POST.get('id'))
        except District.DoesNotExist:
            messages.error(request, "Ce district n'existe pas.")
            return HttpResponseRedirect(reverse('localisation:localisation'))


        if district:
            # On format les chaine
            code = request.POST.get("code")
            libelle = request.POST.get("libelle")
            libelle = libelle.capitalize()

            district.code = code
            district.libelle = libelle
            district.save()

            messages.success(request, "Modification réussie.")

            return HttpResponseRedirect(reverse('localisation:localisation'))
    else:
        return HttpResponseRedirect(reverse('localisation:localisation'))

@login_required
@permission_required('localisation.delete_district', raise_exception=True)
def supprimer_district(request, id):

    global _active_onglet
    _active_onglet = "district"  # On initialise la variable

    try:
        district = District.objects.get(id=id)
    except District.DoesNotExist:
        messages.error(request, "Ce district n'existe pas.")
        return HttpResponseRedirect(reverse('localisation:localisation'))

    if district:
        district.delete()
        messages.info(request, "Suppression réussie.")

    return HttpResponseRedirect(reverse('localisation:localisation'))

# Fin de la Gestion du district -------------------------------------

# Gestion de la région -----------------------------------------------

@login_required
@permission_required('localisation.add_region', raise_exception=True)
def ajouter_region(request):

    global _active_onglet
    _active_onglet = "region"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        code = request.POST.get("code", None)
        libelle = request.POST.get("libelle", None)
        district = request.POST.get("select_district", None)

        if code and libelle and district:
            # On vérifie si le code et le libelle existe
            # On format les chaine
            libelle = libelle.capitalize()

            try:
                region = Region.objects.get(code = code)
                messages.error(request, f"Ce code :[{code}] existe déjà.")
                return HttpResponseRedirect(reverse('localisation:localisation'))

            except Region.DoesNotExist:
                try:
                    region = Region.objects.get(libelle = libelle)
                    messages.error(request, f"Ce libellé :[{libelle}] existe déjà.")
                    return HttpResponseRedirect(reverse('localisation:localisation'))
                except Region.DoesNotExist:
                    pass
            #----
            region = Region()
            region.code = code
            region.libelle = libelle
            region.district = District.objects.get(id = district)
            region.save()

            messages.success(request,"Enregistrement réussi.")

            return HttpResponseRedirect(reverse('localisation:localisation'))
        else:
            messages.error(request, "Veuillez renseigner les champs.")
            return HttpResponseRedirect(reverse('localisation:localisation'))
    else:
        return HttpResponseRedirect(reverse('localisation:localisation'))

@login_required
@permission_required('localisation.change_region', raise_exception=True)
def modifier_region(request):

    global _active_onglet
    _active_onglet = "region"  # On initialise la variable

    if request.method == "POST":

        try:
            region = Region.objects.get(id=request.POST.get('id'))
        except Region.DoesNotExist:
            messages.error(request, "Cette région n'existe pas.")
            return HttpResponseRedirect(reverse('localisation:localisation'))


        if region:
            # On format les chaine
            code = request.POST.get("code")
            libelle = request.POST.get("libelle")
            district = request.POST.get("select_district")
            libelle = libelle.capitalize()

            region.code = code
            region.libelle = libelle
            region.district = District.objects.get(id = district)
            region.save()

            messages.success(request, "Modification réussie.")

            return HttpResponseRedirect(reverse('localisation:localisation'))
    else:
        return HttpResponseRedirect(reverse('localisation:localisation'))

@login_required
@permission_required('localisation.delete_region', raise_exception=True)
def supprimer_region(request, id):

    global _active_onglet
    _active_onglet = "region"  # On initialise la variable

    try:
        region = Region.objects.get(id=id)
    except District.DoesNotExist:
        messages.error(request, "Cette région n'existe pas.")
        return HttpResponseRedirect(reverse('localisation:localisation'))

    if region:
        region.delete()
        messages.info(request, "Suppression réussie.")

    return HttpResponseRedirect(reverse('localisation:localisation'))

@login_required
@permission_required('localisation.view_region', raise_exception=True)
def details_region(request):

    if request.method == "GET":
        id = request.GET.get('id', None)
        if id:
            ajax_regions = Region.objects.filter(district=id).order_by('libelle')

            if ajax_regions:

localisation/templates/localisation/ajouter_commune.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="communeModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}communeModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}communeModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-warehouse"></i>{% block modal-titre %} Ajouter une commune {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'localisation:ajouter_commune' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-qrcode"></i></span>
                  </div>
                  <input type="text" name="code" class="form-control" placeholder="Saisir le code" {% block value-code %}{% endblock value-code %} required>
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-warehouse"></i></span>
                  </div>
                  <input type="text" name="libelle" class="form-control" {% block value-libelle %}{% endblock value-libelle %} placeholder="Saisir la commune" required>
              </div>

              {% block select-district %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_district"><i class="fas fa-igloo"></i></label>
                  </div>

                  <select name="select_district" id="select_district" class="form-control" required>
                      <option value="" selected>--- Sélectionnez un district ---</option>
                      {% for district in districts %}
                      <option value="{{district.id}}" >{{district.libelle}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-district %}

              {% block select-region %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_region"><i class="fas fa-home"></i></label>
                  </div>

                  <select name="select_region" id="select_region" class="form-control" required>
                      <option value="" selected>--- Sélectionnez une région ---</option>
                  </select>
              </div>
              {% endblock select-region %}

              {% block select-departement %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_departement"><i class="fas fa-building"></i></label>
                  </div>

                  <select name="select_departement" id="select_departement" class="form-control" required>
                      <option value="" selected>--- Sélectionnez un département ---</option>
                  </select>
              </div>
              {% endblock select-departement %}

              {% block select-ville %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_ville"><i class="fas fa-city"></i></label>
                  </div>

                  <select name="select_ville" id="select_ville" class="form-control" required>
                      <option value="" selected>--- Sélectionnez une ville ---</option>
                  </select>
              </div>
              {% endblock select-ville %}

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

localisation/templates/localisation/ajouter_departement.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="departementModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}departementModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}departementModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-building"></i>{% block modal-titre %} Ajouter un département {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'localisation:ajouter_departement' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-qrcode"></i></span>
                  </div>
                  <input type="text" name="code" class="form-control" placeholder="Saisir le code" {% block value-code %}{% endblock value-code %} required autofocus >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-building"></i></span>
                  </div>
                  <input type="text" name="libelle" class="form-control" {% block value-libelle %}{% endblock value-libelle %} placeholder="Saisir le département" required>
              </div>

              {% block select-district %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_district"><i class="fas fa-igloo"></i></label>
                  </div>

                  <select name="select_district" id="select_district" class="form-control" required>
                      <option value="" selected>---Sélectionnez un district---</option>
                      {% for district in districts %}
                      <option value="{{district.id}}" >{{district.libelle}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-district %}

              {% block select-region %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_region"><i class="fas fa-home"></i></label>
                  </div>

                  <select name="select_region" id="select_region" class="form-control" required>
                      <option value="" selected>---Sélectionnez une région---</option>
                  </select>
              </div>
              {% endblock select-region %}

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

localisation/templates/localisation/ajouter_district.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="ajouterModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}addModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}addModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-igloo"></i>{% block modal-titre %} Ajouter un district {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'localisation:ajouter_district' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-qrcode"></i></span>
                  </div>
                  <input type="text" name="code" class="form-control" placeholder="Saisir le code" {% block value-code %}{% endblock value-code %} required autofocus >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-igloo"></i></span>
                  </div>
                  <input type="text" name="libelle" class="form-control" {% block value-libelle %}{% endblock value-libelle %} placeholder="Saisir le district" required>
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

localisation/templates/localisation/modifier_district.html
{% extends 'localisation/ajouter_district.html' %}

{% block modal-id %} id="modifierModal{{district.id}}" {% endblock modal-id %}
{% block modal-label %}modifierModalLabel{{district.id}}{% endblock modal-label %}
{% block modal-label2 %}modifierModalLabel{{district.id}}{% endblock modal-label2 %}
{% block modal-titre %} Modifier un district {% endblock modal-titre %}
{% block action %} action="{% url 'localisation:modifier_district' %}" {% endblock action %}
{% block modifier-id %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="text" name="id" class="form-control" value="{{district.id}}" readonly >
    </div>
{% endblock modifier-id %}
{% block value-code %}value="{{district.code}}"{% endblock value-code %}
{% block value-libelle %}value="{{district.libelle}}"{% endblock value-libelle %}
{% block btn-action %}<i class="fas fa-pen"></i> Modifier {% endblock btn-action %}