etat/urls.py
from django.urls import path
from . import views

app_name = 'etat'
urlpatterns = [
    path('', views.etat, name='etat'),

    # Url des bouttons Membre
    path('fiche-identification', views.fiche_identification, name='fiche_identification'),
    path('retour-etat/<str:id>', views.retour_etat, name='retour_etat'),
    path('liste-badge', views.liste_badge, name='liste_badge'),
    path('total-enfants', views.total_enfants, name='total_enfants'),
    path('nouvelle-naissance', views.nouvelle_naissance, name='nouvelle_naissance'),
    path('total-deces', views.total_deces, name='total_deces'),
    path('total-deces-enfant', views.total_deces_enfant, name='total_deces_enfant'),
    path('total-accident', views.total_accident, name='total_accident'),
    path('total-accident-enfant', views.total_accident_enfant, name='total_accident_enfant'),

    # Url des bouttons Coopérative et groupement
    path('liste-secteur-activite', views.liste_secteur_activite, name='liste_secteur_activite'),
    path('liste-membre', views.liste_membre, name='liste_membre'),

]

projet/urls.py
"""projet URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler400, handler403
from django.conf.urls.static import static

# Configuration des erreurs
handler404 = 'utilisateur.views.handler404'
handler500 = 'utilisateur.views.handler500'
handler400 = 'utilisateur.views.handler400'
handler403 = 'utilisateur.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('localisation/', include('localisation.urls')),
    path('etatcivil/', include('etatcivil.urls')),
    path('vieprofessionnelle/', include('vieprofessionnelle.urls')),
    path('presentation/', include('presentation.urls')),
    path('etat/', include('etat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vieprofessionnelle/urls.py
from django.urls import path
from . import views

app_name = 'vieprofessionnelle'
urlpatterns = [
    path('', views.vieprofessionnelle, name = 'vieprofessionnelle'),

    # Url du Type Secteur d'activité
    path('ajouter-typesecteur', views.ajouter_typesecteur, name = 'ajouter_typesecteur'),
    path('modifier-typesecteur', views.modifier_typesecteur, name = 'modifier_typesecteur'),
    path('supprimer-typesecteur/<str:id>', views.supprimer_typesecteur, name = 'supprimer_typesecteur'),

    # Url du Secteur
    path('ajouter-secteur', views.ajouter_secteur, name='ajouter_secteur'),
    path('modifier-secteur', views.modifier_secteur, name='modifier_secteur'),
    path('supprimer-secteur/<str:id>', views.supprimer_secteur, name='supprimer_secteur'),
    path('details-secteur', views.details_secteur, name='details_secteur'),
    path('details-activite', views.details_activite, name='details_activite'),

    # Url Type de Parent
    path('ajouter-typeparent', views.ajouter_typeparent, name='ajouter_typeparent'),
    path('modifier-typeparent', views.modifier_typeparent, name='modifier_typeparent'),
    path('supprimer-typeparent/<str:id>', views.supprimer_typeparent, name='supprimer_typeparent'),

    # Url Parent
    path('ajouter-parent', views.ajouter_parent, name='ajouter_parent'),
    path('modifier-parent', views.modifier_parent, name='modifier_parent'),
    path('supprimer-parent/<str:id>', views.supprimer_parent, name='supprimer_parent'),

    # Url Type d'état de santé
    path('ajouter-typeetatsante', views.ajouter_typeetatsante, name='ajouter_typeetatsante'),
    path('modifier-typeetatsante', views.modifier_typeetatsante, name='modifier_typeetatsante'),
    path('supprimer-typeetatsante/<str:id>', views.supprimer_typeetatsante, name='supprimer_typeetatsante'),

    # Url Type d'état de document
    path('ajouter-typedocument', views.ajouter_typedocument, name='ajouter_typedocument'),
    path('modifier-typedocument', views.modifier_typedocument, name='modifier_typedocument'),
    path('supprimer-typedocument/<str:id>', views.supprimer_typedocument, name='supprimer_typedocument'),

    # Url Type du document
    path('ajouter-document/', views.ajouter_document, name='ajouter_document'),
    path('modifier-document/', views.modifier_document, name='modifier_document'),
    path('supprimer-document/<str:id>', views.supprimer_document, name='supprimer_document'),

    # Url Coopérative
    path('ajouter-cooperative', views.ajouter_cooperative, name='ajouter_cooperative'),
    # Url Groupement
    path('ajouter-groupement', views.ajouter_groupement, name='ajouter_groupement'),

    # Url Chapeau
    path('ajouter-chapeau/', views.ajouter_chapeau, name='ajouter_chapeau'),
    path('modifier-chapeau/', views.modifier_chapeau, name='modifier_chapeau'),
    path('supprimer-chapeau/<str:id>', views.supprimer_chapeau, name='supprimer_chapeau'),

    # Url TypePersonneRessource
    path('ajouter-typepersonneressource/', views.ajouter_typepersonneressource, name='ajouter_typepersonneressource'),
    path('modifier-typepersonneressource/', views.modifier_typepersonneressource, name='modifier_typepersonneressource'),
    path('supprimer-typepersonneressource/<str:id>', views.supprimer_typepersonneressource, name='supprimer_typepersonneressource'),

    # Url PersonneRessource
    path('ajouter-personneressource', views.ajouter_personneressource, name='ajouter_personneressource'),
    path('supprimer-personneressource', views.supprimer_personneressource, name='supprimer_personneressource'),
    path('details-personneressource', views.details_personneressource, name='details_personneressource'),

    # Url TypeResponsabilité
    path('ajouter-typeresponsabilite/', views.ajouter_typeresponsabilite, name='ajouter_typeresponsabilite'),
    path('modifier-typeresponsabilite/', views.modifier_typeresponsabilite, name='modifier_typeresponsabilite'),
    path('supprimer-typeresponsabilite/<str:id>', views.supprimer_typeresponsabilite, name='supprimer_typeresponsabilite'),

    # Url MontantFinancement
    path('ajouter-montantfinancement/', views.ajouter_montantfinancement, name='ajouter_montantfinancement'),
    path('modifier-montantfinancement/', views.modifier_montantfinancement, name='modifier_montantfinancement'),
    path('supprimer-montantfinancement/<str:id>', views.supprimer_montantfinancement, name='supprimer_montantfinancement'),

    # Url QuantiteGroupement
    path('ajouter-quantitegroupement/', views.ajouter_quantitegroupement, name='ajouter_quantitegroupement'),
    path('modifier-quantitegroupement/', views.modifier_quantitegroupement, name='modifier_quantitegroupement'),
    path('supprimer-quantitegroupement/<str:id>', views.supprimer_quantitegroupement, name='supprimer_quantitegroupement'),


]

vieprofessionnelle/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse
import os
from datetime import datetime
from django.utils.html import strip_tags
from utilisateur.models import Parametre


# Les constatntes et les variables globales
_active_onglet = ""  # Variable globale pour l'activation des onglets

@login_required
@permission_required('vieprofessionnelle.view_membre', raise_exception=True)
def vieprofessionnelle(request):
    typesecteurs = TypeSecteur.objects.order_by("type")
    secteurs = Secteur.objects.order_by("secteur")
    typeparents = TypeParent.objects.order_by("libelle")
    parents = Parent.objects.order_by("nomprenoms")
    typeetatsantes = TypeEtatSante.objects.order_by("libelle")
    typedocuments = TypeDocument.objects.order_by("libelle")
    documents = Document.objects.order_by("-id")
    chapeaux = Chapeau.objects.order_by("-id")
    typepersonneressources = TypePersonneRessource.objects.order_by("-id")
    personneressources = PersonneRessource.objects.order_by("-id")
    membres = Membre.objects.filter(actif=True).order_by("nom_prenoms")
    typeresponsabilites = TypeResponsabilite.objects.order_by("-id")
    montantfinancements = MontantFinancement.objects.order_by("montant")
    quantitegroupements = QuantiteGroupement.objects.order_by("quantite")

    # Initialisation de l'affichage de l'onglet active
    active_typesecteur = ['', 'false', '']
    active_secteur = ['', 'false', '']
    active_typeparent = ['', 'false', '']
    active_parent = ['', 'false', '']
    active_typeetatsante = ['', 'false', '']
    active_typedocument = ['', 'false', '']
    active_document = ['', 'false', '']
    active_chapeau = ['', 'false', '']
    active_typepersonneressource = ['', 'false', '']
    active_personneressource = ['', 'false', '']
    active_typeresponsabilite = ['', 'false', '']
    active_montantfinancement = ['', 'false', '']
    active_quantitegroupement = ['', 'false', '']

    if _active_onglet == "typesecteur":
        active_typesecteur = ['active', 'true', 'show active']
    elif _active_onglet == "secteur":
        active_secteur = ['active', 'true', 'show active']
    elif _active_onglet == "typeparent":
        active_typeparent = ['active', 'true', 'show active']
    elif _active_onglet == "parent":
        active_parent = ['active', 'true', 'show active']
    elif _active_onglet == "typeetatsante":
        active_typeetatsante = ['active', 'true', 'show active']
    elif _active_onglet == "typedocument":
        active_typedocument = ['active', 'true', 'show active']
    elif _active_onglet == "document":
        active_document = ['active', 'true', 'show active']
    elif _active_onglet == "chapeau":
        active_chapeau = ['active', 'true', 'show active']
    elif _active_onglet == "typepersonneressource":
        active_typepersonneressource = ['active', 'true', 'show active']
    elif _active_onglet == "personneressource":
        active_personneressource = ['active', 'true', 'show active']
    elif _active_onglet == "typeresponsabilite":
        active_typeresponsabilite = ['active', 'true', 'show active']
    elif _active_onglet == "montantfinancement":
        active_montantfinancement = ['active', 'true', 'show active']
    elif _active_onglet == "quantitegroupement":
        active_quantitegroupement = ['active', 'true', 'show active']
    else:
        # Affichage par défaut
        active_typesecteur = ['active', 'true', 'show active']

    context = {
        "titre": "Vie professionnelle",
        "typesecteurs": typesecteurs,
        "secteurs": secteurs,
        "typeparents": typeparents,
        "parents": parents,
        "typeetatsantes": typeetatsantes,
        "typedocuments": typedocuments,
        "documents": documents,
        "membres": membres,
        "chapeaux": chapeaux,
        "typepersonneressources": typepersonneressources,
        "personneressources": personneressources,
        "id_chapeau": int(Parametre.objects.first().id_chapeau),
        "monnaie": Parametre.objects.first().monnaie,
        "typeresponsabilites": typeresponsabilites,
        "montantfinancements": montantfinancements,
        "quantitegroupements": quantitegroupements,

        "active_typesecteur": active_typesecteur,
        "active_secteur": active_secteur,
        "active_typeparent": active_typeparent,
        "active_parent": active_parent,
        "active_typeetatsante": active_typeetatsante,
        "active_typedocument": active_typedocument,
        "active_document": active_document,
        "active_chapeau": active_chapeau,
        "active_typepersonneressource": active_typepersonneressource,
        "active_personneressource": active_personneressource,
        "active_typeresponsabilite": active_typeresponsabilite,
        "active_montantfinancement": active_montantfinancement,
        "active_quantitegroupement": active_quantitegroupement,

    }

    return render(request, "vieprofessionnelle/vieprofessionnelle.html", context)

# Gestion du type de secteur -----------------------------------------------
@login_required
@permission_required('vieprofessionnelle.add_typesecteur', raise_exception=True)
def ajouter_typesecteur(request):
    global _active_onglet
    _active_onglet = "typesecteur"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        type = request.POST.get("type", None)

        if type:  # On vérifie si les champs ont été renseignés

            # On format les chaines
            type = type.upper()

            try:
                objet_typesecteur = TypeSecteur.objects.get(type=type)
                messages.error(request, f"Ce type :[{type}] existe déjà.")
                return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))

            except TypeSecteur.DoesNotExist:
                pass

            # ----
            objet_typesecteur = TypeSecteur()
            objet_typesecteur.type = type
            objet_typesecteur.save()

            messages.success(request, "Enregistrement réussi.")

            return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))
    else:
        return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))


@login_required
@permission_required('vieprofessionnelle.change_typesecteur', raise_exception=True)
def modifier_typesecteur(request):
    global _active_onglet
    _active_onglet = "typesecteur"  # On initialise la variable

    if request.method == "POST":

        try:
            objet_typesecteur = TypeSecteur.objects.get(id=request.POST.get('id'))
        except TypeSecteur.DoesNotExist:
            messages.error(request, "Ce type de secteur n'existe pas.")
            return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))

        if objet_typesecteur:
            # On format les chaine
            type_nouveau = request.POST.get("type", None)
            type_nouveau = type_nouveau.upper()

            # On récupère l'ancienne valeur
            type_ancien = objet_typesecteur.type

            # On vérifie si la valeur a changé
            if type_nouveau != type_ancien:
                # On vérifie si le valeur modifié existe déjà
                try:
                    TypeSecteur.objects.get(type=type_nouveau)
                    messages.error(request, f"Ce type de secteur [{type_nouveau}] existe déjà.")
                    return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))

                except TypeSecteur.DoesNotExist:
                    pass

            # On effectue la modification
            objet_typesecteur.type = type_nouveau
            objet_typesecteur.save()

            messages.success(request, "Modification réussie.")

            return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))
    else:
        return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))


@login_required
@permission_required('vieprofessionnelle.delete_typesecteur', raise_exception=True)
def supprimer_typesecteur(request, id):
    global _active_onglet
    _active_onglet = "typesecteur"  # On initialise la variable

    try:
        objet_typesecteur = TypeSecteur.objects.get(id=id)
    except TypeSecteur.DoesNotExist:
        messages.error(request, "Ce type de secteur n'existe pas.")
        return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))

    if objet_typesecteur:
        objet_typesecteur.delete()
        messages.info(request, "Suppression réussie.")

    return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))
# Fin de la Gestion du type de secteur -------------------------------------

# Gestion du secteur -----------------------------------------------
@login_required
@permission_required('vieprofessionnelle.add_secteur', raise_exception=True)
def ajouter_secteur(request):
    global _active_onglet
    _active_onglet = "secteur"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        secteur = request.POST.get("secteur", None)
        typesecteur = request.POST.get("select_typesecteur", None)

        if secteur and typesecteur:  # On vérifie si les champs ont été renseignés

            # On format les chaines
            secteur = secteur.capitalize()

            try:
                objet_secteur = Secteur.objects.get(secteur=secteur)
                messages.error(request, f"Ce secteur :[{secteur}] existe déjà.")
                return HttpResponseRedirect(reverse('vieprofessionnelle:vieprofessionnelle'))

            except Secteur.DoesNotExist:
                pass

            # ----
            objet_secteur = Secteur()
            objet_secteur.secteur = secteur

vieprofessionnelle/templates/vieprofessionnelle/ajouter_document.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="documentModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}documentModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}documentModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-file-image"></i>{% block modal-titre %} Ajouter un document {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'vieprofessionnelle:ajouter_document' %}" {% endblock action %} autocomplete="off" enctype="multipart/form-data">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              {% block select-membre %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_membre"><i class="fas fa-user"></i></label>
                  </div>

                  <select name="select_membre" id="select_membre" class="form-control" required>
                      <option value="" selected>--- Sélectionnez un propriétaire ---</option>
                      {% for membre in membres %}
                      <option value="{{membre.id}}" >{{membre.nom|title}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-membre %}

              {% block select-typedocument %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_typedocument"><i class="fas fa-paste"></i></label>
                  </div>

                  <select name="select_typedocument" id="select_typedocument" class="form-control" required>
                      <option value="" selected>--- Sélectionnez un type de document ---</option>
                      {% for typedocument in typedocuments %}
                      <option value="{{typedocument.id}}" >{{typedocument.libelle|capfirst}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-typedocument %}

              {% block value-image %}{% endblock value-image %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-image"></i></span>
                  </div>
                  <input type="file" name="photo" class="form-control" {% block value-photo %}{% endblock value-photo %} >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                  </div>
                  <input type="date" name="dateenre" value="{% now 'Y-m-d' %}" class="form-control" {% block value-date %}{% endblock value-date %} >
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

vieprofessionnelle/templates/vieprofessionnelle/ajouter_montantfinancement.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="montantfinancementModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}montantfinancementModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}montantfinancementModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-money-bill-alt"></i>{% block modal-titre %} Ajouter un montant de financement {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'vieprofessionnelle:ajouter_montantfinancement' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-money-bill-alt"></i></span>
                  </div>
                  <input type="number" min="0" name="montant" class="form-control" placeholder="Montant du financement" {% block value-montant %}{% endblock value-montant %} required autofocus >
                  <div class="input-group-append">
                      <span class="input-group-text">{{monnaie}}</span>
                  </div>
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

vieprofessionnelle/templates/vieprofessionnelle/ajouter_parent.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="parentModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}parentModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}parentModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-user-check"></i>{% block modal-titre %} Ajouter un parent {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'vieprofessionnelle:ajouter_parent' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              {% block select-typeparent %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_typeparent"><i class="fas fa-user-friends"></i></label>
                  </div>

                  <select name="select_typeparent" id="select_typeparent" class="form-control" required>
                      <option value="" selected>--- Sélectionnez un type de parent ---</option>
                      {% for typeparent in typeparents %}
                      <option value="{{typeparent.id}}" >{{typeparent.libelle|capfirst}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-typeparent %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-user-check"></i></span>
                  </div>
                  <input type="text" name="nomprenoms" class="form-control" placeholder="Saisir le nom et prénoms" {% block value-nomprenoms %}{% endblock value-nomprenoms %} required autofocus >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                  </div>
                  <input type="date" name="datenaissance" class="form-control" {% block value-date %}{% endblock value-date %} >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                  </div>
                  <input type="text" name="adresse" class="form-control" placeholder="Adresse" {% block value-adresse %}{% endblock value-adresse %} >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-phone"></i></span>
                  </div>
                  <input type="text" name="contact" class="form-control" placeholder="Contacts" {% block value-contact %}{% endblock value-contact %} >
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  {% block btn-ajax %}
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
                  {% endblock btn-ajax %}
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

vieprofessionnelle/templates/vieprofessionnelle/ajouter_typepersonneressource.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="typepersonneressourceModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}typepersonneressourceModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}typepersonneressourceModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-user-tie"></i>{% block modal-titre %} Ajouter un type de personne ressource {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'vieprofessionnelle:ajouter_typepersonneressource' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-user-tie"></i></span>
                  </div>
                  <input type="text" name="type" class="form-control" placeholder="Saisir le type" {% block value-type %}{% endblock value-type %} required autofocus >
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

vieprofessionnelle/templates/vieprofessionnelle/modifier_montantfinancement.html
{% extends 'vieprofessionnelle/ajouter_montantfinancement.html' %}

{% block modal-id %} id="montantfinancementmodifierModal{{montantfinancement.id}}" {% endblock modal-id %}
{% block modal-label %}montantfinancementModalLabel{{montantfinancement.id}}{% endblock modal-label %}
{% block modal-label2 %}montantfinancementModalLabel{{montantfinancement.id}}{% endblock modal-label2 %}
{% block modal-titre %} Modifier un mont de financement {% endblock modal-titre %}
{% block action %} action="{% url 'vieprofessionnelle:modifier_montantfinancement' %}" {% endblock action %}
{% block modifier-id %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="text" name="id" class="form-control" value="{{montantfinancement.id}}" readonly >
    </div>
{% endblock modifier-id %}

{% block value-montant %}value="{{montantfinancement.montant}}"{% endblock value-montant %}
{% block btn-action %}<i class="fas fa-pen"></i> Modifier {% endblock btn-action %}