etat/urls.py
from django.urls import path
from . import views

app_name = 'etat'
urlpatterns = [
    path('', views.etat, name='etat'),

    # Url des bouttons Membre
    path('fiche-identification', views.fiche_identification, name='fiche_identification'),
    path('retour-etat/<str:id>', views.retour_etat, name='retour_etat'),
    path('liste-badge', views.liste_badge, name='liste_badge'),
    path('total-enfants', views.total_enfants, name='total_enfants'),
    path('nouvelle-naissance', views.nouvelle_naissance, name='nouvelle_naissance'),
    path('total-deces', views.total_deces, name='total_deces'),
    path('total-deces-enfant', views.total_deces_enfant, name='total_deces_enfant'),
    path('total-accident', views.total_accident, name='total_accident'),
    path('total-accident-enfant', views.total_accident_enfant, name='total_accident_enfant'),

    # Url des bouttons Coopérative et groupement
    path('liste-secteur-activite', views.liste_secteur_activite, name='liste_secteur_activite'),
    path('liste-membre', views.liste_membre, name='liste_membre'),

]

etatcivil/urls.py
from django.urls import path
from . import views

app_name = 'etatcivil'
urlpatterns = [
    path('', views.etatcivil, name = 'etatcivil'),

    # Url du type de pièce
    path('ajouter-typepiece', views.ajouter_typepiece, name = 'ajouter_typepiece'),
    path('modifier-typepiece', views.modifier_typepiece, name = 'modifier_typepiece'),
    path('supprimer-typepiece/<str:id>', views.supprimer_typepiece, name = 'supprimer_typepiece'),

    # Url du niveau
    path('ajouter-niveau', views.ajouter_niveau, name = 'ajouter_niveau'),
    path('modifier-niveau', views.modifier_niveau, name = 'modifier_niveau'),
    path('supprimer-niveau/<str:id>', views.supprimer_niveau, name = 'supprimer_niveau'),

    # Url du niveau scolaire
    path('ajouter-niveauscolaire', views.ajouter_niveauscolaire, name='ajouter_niveauscolaire'),
    path('modifier-niveauscolaire', views.modifier_niveauscolaire, name='modifier_niveauscolaire'),
    path('supprimer-niveauscolaire/<str:id>', views.supprimer_niveauscolaire, name='supprimer_niveauscolaire'),

    # Url du sexe
    path('ajouter-sexe', views.ajouter_sexe, name='ajouter_sexe'),
    path('modifier-sexe', views.modifier_sexe, name='modifier_sexe'),
    path('supprimer-sexe/<str:id>', views.supprimer_sexe, name='supprimer_sexe'),

    # Url du Nationalité
    path('ajouter-nationalite', views.ajouter_nationalite, name='ajouter_nationalite'),
    path('modifier-nationalite', views.modifier_nationalite, name='modifier_nationalite'),
    path('supprimer-nationalite/<str:id>', views.supprimer_nationalite, name='supprimer_nationalite'),

    # Url du Situation matrimoniale
    path('ajouter-situationmatrimoniale', views.ajouter_situationmatrimoniale, name='ajouter_situationmatrimoniale'),
    path('modifier-situationmatrimoniale', views.modifier_situationmatrimoniale, name='modifier_situationmatrimoniale'),
    path('supprimer-situationmatrimoniale/<str:id>', views.supprimer_situationmatrimoniale, name='supprimer_situationmatrimoniale'),

]

projet/urls.py
"""projet URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler400, handler403
from django.conf.urls.static import static

# Configuration des erreurs
handler404 = 'utilisateur.views.handler404'
handler500 = 'utilisateur.views.handler500'
handler400 = 'utilisateur.views.handler400'
handler403 = 'utilisateur.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('localisation/', include('localisation.urls')),
    path('etatcivil/', include('etatcivil.urls')),
    path('vieprofessionnelle/', include('vieprofessionnelle.urls')),
    path('presentation/', include('presentation.urls')),
    path('etat/', include('etat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etatcivil/models.py
from django.db import models

class TypePiece(models.Model):
    type = models.CharField(max_length=100, unique=True)
    libelle = models.CharField(max_length=250, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle

class Niveau(models.Model):
    niveau = models.CharField(max_length=250, verbose_name="Niveau", unique=True)

    def __str__(self):
        return self.niveau

class NiveauScolaire(models.Model):
    classe = models.CharField(max_length=250, verbose_name="Classe", unique=True)
    niveau = models.ForeignKey(Niveau,null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.classe

class Sexe(models.Model):
    code = models.CharField(max_length=1, unique=True)
    libelle = models.CharField(max_length=50, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle

class Nationalite(models.Model):
    code = models.CharField(max_length=3, unique=True)
    nationalite = models.CharField(max_length=100, verbose_name="Nationalité", unique=True)
    pays = models.CharField(max_length=250, verbose_name="Pays", unique=True)

    def __str__(self):
        return self.nationalite

class SituationMatrimoniale(models.Model):
    situation = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.situation

etatcivil/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse

# Les constatntes et les variables globales
_active_onglet = "" # Variable globale pour l'activation des onglets

@login_required
@permission_required('vieprofessionnelle.view_membre', raise_exception=True)
def etatcivil(request):

    typepieces = TypePiece.objects.all().order_by("libelle")
    niveaux = Niveau.objects.all().order_by("id")
    niveauscolaires = NiveauScolaire.objects.all().order_by("id")
    sexes = Sexe.objects.all().order_by("id")
    nationalites = Nationalite.objects.all().order_by("nationalite")
    situations = SituationMatrimoniale.objects.all().order_by("id")

    # Initialisation de l'affichage de l'onglet active
    active_typepiece = ['','false','']
    active_niveau = ['','false','']
    active_niveauscolaire = ['','false','']
    active_sexe = ['','false','']
    active_nationalite = ['','false','']
    active_situation = ['','false','']

    if _active_onglet == "typepiece":
        active_typepiece =  ['active', 'true', 'show active']
    elif _active_onglet == "niveau":
        active_niveau =  ['active', 'true', 'show active']
    elif _active_onglet == "niveauscolaire":
        active_niveauscolaire =  ['active', 'true', 'show active']
    elif _active_onglet == "sexe":
        active_sexe =  ['active', 'true', 'show active']
    elif _active_onglet == "nationalite":
        active_nationalite =  ['active', 'true', 'show active']
    elif _active_onglet == "situation":
        active_situation =  ['active', 'true', 'show active']
    else:
        # Affichage par défaut
        active_typepiece =  ['active', 'true', 'show active']


    context = {
        "titre" : "Etat civil",
        "typepieces" : typepieces,
        "niveaux" : niveaux,
        "niveauscolaires" : niveauscolaires,
        "sexes" : sexes,
        "nationalites" : nationalites,
        "situations" : situations,

        "active_typepiece": active_typepiece,
        "active_niveau": active_niveau,
        "active_niveauscolaire": active_niveauscolaire,
        "active_sexe": active_sexe,
        "active_nationalite": active_nationalite,
        "active_situation": active_situation,

    }

    return render(request, "etatcivil/etatcivil.html", context)

# Gestion du type de pièce -----------------------------------------------

@login_required
@permission_required('etatcivil.add_typepiece', raise_exception=True)
def ajouter_typepiece(request):

    global _active_onglet
    _active_onglet = "typepiece"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        type = request.POST.get("type", None)
        libelle = request.POST.get("libelle", None)

        if type and libelle:
            # On vérifie si le code et le libelle existe
            # On format les chaine
            type = type.upper()
            libelle = libelle.upper()

            try:
                typepiece = TypePiece.objects.get(type = type)
                messages.error(request, f"Ce code :[{type}] existe déjà.")
                return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

            except TypePiece.DoesNotExist:
                try:
                    typepiece = TypePiece.objects.get(libelle = libelle)
                    messages.error(request, f"Ce libellé :[{libelle}] existe déjà.")
                    return HttpResponseRedirect(reverse('etatcivil:etatcivil'))
                except TypePiece.DoesNotExist:
                    pass
            #----
            typepiece = TypePiece()
            typepiece.type = type
            typepiece.libelle = libelle
            typepiece.save()

            messages.success(request,"Enregistrement réussi.")

            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))
    else:
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

@login_required
@permission_required('etatcivil.change_typepiece', raise_exception=True)
def modifier_typepiece(request):

    global _active_onglet
    _active_onglet = "typepiece"  # On initialise la variable

    if request.method == "POST":

        try:
            typepiece = TypePiece.objects.get(id=request.POST.get('id'))
        except TypePiece.DoesNotExist:
            messages.error(request, "Ce type de pièce n'existe pas.")
            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))


        if typepiece:
            # On format les chaine
            type = request.POST.get("type")
            libelle = request.POST.get("libelle")
            type = type.upper()
            libelle = libelle.upper()

            typepiece.type = type
            typepiece.libelle = libelle
            typepiece.save()

            messages.success(request, "Modification réussie.")

            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))
    else:
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

@login_required
@permission_required('etatcivil.delete_typepiece', raise_exception=True)
def supprimer_typepiece(request, id):

    global _active_onglet
    _active_onglet = "typepiece"  # On initialise la variable

    try:
        typepiece = TypePiece.objects.get(id=id)
    except TypePiece.DoesNotExist:
        messages.error(request, "Ce type de pièce n'existe pas.")
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

    if typepiece:
        typepiece.delete()
        messages.info(request, "Suppression réussie.")

    return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

# Fin de la Gestion du type de pièce -------------------------------------

# Gestion du niveau -----------------------------------------------

@login_required
@permission_required('etatcivil.add_niveau', raise_exception=True)
def ajouter_niveau(request):

    global _active_onglet
    _active_onglet = "niveau"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        niveau = request.POST.get("niveau", None)

        if niveau:
            # On vérifie si le niveau existe
            # On format les chaine
            niveau = niveau.capitalize()

            try:
                niveaux = Niveau.objects.get(niveau = niveau)
                messages.error(request, f"Ce niveau :[{niveau}] existe déjà.")
                return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

            except Niveau.DoesNotExist:
                pass
            #----
            niveaux = Niveau()
            niveaux.niveau = niveau
            niveaux.save()

            messages.success(request,"Enregistrement réussi.")

            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))
    else:
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

@login_required
@permission_required('etatcivil.change_niveau', raise_exception=True)
def modifier_niveau(request):

    global _active_onglet
    _active_onglet = "niveau"  # On initialise la variable

    if request.method == "POST":

        try:
            niveaux = Niveau.objects.get(id=request.POST.get('id'))
        except Niveau.DoesNotExist:
            messages.error(request, "Ce niveau n'existe pas.")
            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))


        if niveaux:
            # On format les chaine
            niveau_nouveau = request.POST.get("niveau")
            niveau_nouveau = niveau_nouveau.capitalize()

            # On récupère l'ancienne valeur
            ancien_niveau = niveaux.niveau

            # On vérifie si le niveau a changé
            if niveau_nouveau != ancien_niveau:
                # On vérifie si le niveau modifié existe déjà
                try:
                    niveau_test = Niveau.objects.get(niveau = niveau_nouveau)
                    messages.error(request, "Ce Niveau existe déjà.")
                    return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

                except Niveau.DoesNotExist:
                    pass

            niveaux.niveau = niveau_nouveau
            niveaux.save()

            messages.success(request, "Modification réussie.")

            return HttpResponseRedirect(reverse('etatcivil:etatcivil'))
    else:
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

@login_required
@permission_required('etatcivil.delete_niveau', raise_exception=True)
def supprimer_niveau(request, id):

    global _active_onglet
    _active_onglet = "niveau"  # On initialise la variable

    try:
        niveaux = Niveau.objects.get(id=id)
    except Niveau.DoesNotExist:
        messages.error(request, "Ce niveau n'existe pas.")
        return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

    if niveaux:
        niveaux.delete()
        messages.info(request, "Suppression réussie.")

    return HttpResponseRedirect(reverse('etatcivil:etatcivil'))

# Fin de la Gestion du niveau -------------------------------------

# Gestion du niveau scolaire -----------------------------------------------
@login_required
@permission_required('etatcivil.add_niveauscolaire', raise_exception=True)
def ajouter_niveauscolaire(request):

    global _active_onglet
    _active_onglet = "niveauscolaire"  # On initialise la variable

    if request.method == "POST":
        # On initialise les variables
        classe = request.POST.get("classe", None)
        select_niveau = request.POST.get("select_niveau", None)

        if classe and select_niveau:
            # On vérifie si la classe existe
            # On format les chaine
            classe = classe.upper()

            try:
                niveauscolaire = NiveauScolaire.objects.get(classe = classe)
                messages.error(request, f"Cette classe :[{classe}] existe déjà.")

etatcivil/templates/etatcivil/ajouter_nationalite.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="nationaliteModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}nationaliteModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}nationaliteModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-flag"></i>{% block modal-titre %} Ajouter une nationalité {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'etatcivil:ajouter_nationalite' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-qrcode"></i></span>
                  </div>
                  <input type="text" name="code" class="form-control" placeholder="Saisir le code" {% block value-code %}{% endblock value-code %} required autofocus >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-flag"></i></span>
                  </div>
                  <input type="text" name="nationalite" class="form-control" {% block value-nationalite %}{% endblock value-nationalite %} placeholder="Saisir la nationalité" required>
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-globe"></i></span>
                  </div>
                  <input type="text" name="pays" class="form-control" {% block value-pays %}{% endblock value-pays %} placeholder="Saisir le pays" required>
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

etatcivil/templates/etatcivil/ajouter_niveau.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="niveauModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}niveauModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}niveauModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-graduation-cap"></i>{% block modal-titre %} Ajouter un niveau {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'etatcivil:ajouter_niveau' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-graduation-cap"></i></span>
                  </div>
                  <input type="text" name="niveau" class="form-control" placeholder="Saisir le niveau" {% block value-niveau %}{% endblock value-niveau %} required autofocus >
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

etatcivil/templates/etatcivil/ajouter_niveauscolaire.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="scolaireModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}scolaireModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}scolaireModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-user-graduate"></i>{% block modal-titre %} Ajouter un niveau scolaire {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'etatcivil:ajouter_niveauscolaire' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-user-graduate"></i></span>
                  </div>
                  <input type="text" name="classe" class="form-control" placeholder="Saisir la classe" {% block value-classe %}{% endblock value-classe %} required autofocus >
              </div>

              {% block select-niveau %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <label class="input-group-text" for="select_niveau"><i class="fas fa-graduation-cap"></i></label>
                  </div>

                  <select name="select_niveau" id="select_niveau" required>
                      <option value="" selected>--- Sélectionnez un niveau ---</option>
                      {% for niveau in niveaux %}
                      <option value="{{niveau.id}}" >{{niveau.niveau}}</option>
                      {% endfor %}
                  </select>
              </div>
              {% endblock select-niveau %}

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

etatcivil/templates/etatcivil/ajouter_sexe.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="sexeModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}sexeModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}sexeModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-restroom"></i>{% block modal-titre %} Ajouter un sexe {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'etatcivil:ajouter_sexe' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-qrcode"></i></span>
                  </div>
                  <input type="text" name="code" class="form-control" placeholder="Saisir le code" {% block value-code %}{% endblock value-code %} required autofocus >
              </div>

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-restroom"></i></span>
                  </div>
                  <input type="text" name="libelle" class="form-control" {% block value-libelle %}{% endblock value-libelle %} placeholder="Saisir le libellé" required>
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

etatcivil/templates/etatcivil/ajouter_situation.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="situationModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="{% block modal-label %}situationModalLabel{% endblock modal-label %}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{% block modal-label2 %}situationModalLabel{% endblock modal-label2 %}">
            <i class="fas fa-ring"></i><i class="fas fa-id-card"></i>{% block modal-titre %} Ajouter une situation matrimoniale {% endblock modal-titre %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" {% block action %} action="{% url 'etatcivil:ajouter_situationmatrimoniale' %}" {% endblock action %} autocomplete="off">
          {%  csrf_token %}
          <div class="modal-body">
              {% block modifier-id %}{% endblock modifier-id %}

              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-ring"></i></span>
                  </div>
                  <input type="text" name="situation" class="form-control" placeholder="Saisir la situation" {% block value-situation %}{% endblock value-situation %} required autofocus >
              </div>

          </div>

          <div class="modal-footer text-center">
              <div style="width: 100%;">
                  <button type="submit" class="btn btn-success">
                      {% block btn-action %}<i class="fas fa-plus"></i> Enregistrer {% endblock btn-action %}
                  </button>
                  <button type="reset" class="btn btn-outline-warning" title="Annuler">
                      <i class="fas fa-sync-alt"></i> Annuler
                  </button>
                  <button type="button" class="btn btn-outline-danger" data-dismiss="modal">
                      <i class="fas fa-times"></i> Fermer
                  </button>
              </div>
          </div>

      </form>

    </div>
  </div>
</div>

etatcivil/templates/etatcivil/modifier_nationalite.html
{% extends 'etatcivil/ajouter_nationalite.html' %}

{% block modal-id %} id="nationaliteModal{{nationalite.id}}" {% endblock modal-id %}
{% block modal-label %}nationaliteModalLabel{{nationalite.id}}{% endblock modal-label %}
{% block modal-label2 %}nationaliteModalLabel{{nationalite.id}}{% endblock modal-label2 %}
{% block modal-titre %} Modifier une nationalité {% endblock modal-titre %}
{% block action %} action="{% url 'etatcivil:modifier_nationalite' %}" {% endblock action %}
{% block modifier-id %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="text" name="id" class="form-control" value="{{nationalite.id}}" readonly >
    </div>
{% endblock modifier-id %}
{% block value-code %}value="{{nationalite.code|upper}}"{% endblock value-code %}
{% block value-nationalite %}value="{{nationalite.nationalite|capfirst}}"{% endblock value-nationalite %}
{% block value-pays %}value="{{nationalite.pays|capfirst}}"{% endblock value-pays %}
{% block btn-action %}<i class="fas fa-pen"></i> Modifier {% endblock btn-action %}

etatcivil/templates/etatcivil/modifier_niveau.html
{% extends 'etatcivil/ajouter_niveau.html' %}

{% block modal-id %} id="niveaumodifierModal{{niveau.id}}" {% endblock modal-id %}
{% block modal-label %}niveaumodifierModalLabel{{niveau.id}}{% endblock modal-label %}
{% block modal-label2 %}niveaumodifierModalLabel{{niveau.id}}{% endblock modal-label2 %}
{% block modal-titre %} Modifier un niveau {% endblock modal-titre %}
{% block action %} action="{% url 'etatcivil:modifier_niveau' %}" {% endblock action %}
{% block modifier-id %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="text" name="id" class="form-control" value="{{niveau.id}}" readonly >
    </div>
{% endblock modifier-id %}
{% block value-niveau %}value="{{niveau.niveau}}"{% endblock value-niveau %}
{% block btn-action %}<i class="fas fa-pen"></i> Modifier {% endblock btn-action %}