etat/urls.py
from django.urls import path
from . import views

app_name = 'etat'
urlpatterns = [
    path('', views.etat, name='etat'),

    # Url des bouttons Membre
    path('fiche-identification', views.fiche_identification, name='fiche_identification'),
    path('retour-etat/<str:id>', views.retour_etat, name='retour_etat'),
    path('liste-badge', views.liste_badge, name='liste_badge'),
    path('total-enfants', views.total_enfants, name='total_enfants'),
    path('nouvelle-naissance', views.nouvelle_naissance, name='nouvelle_naissance'),
    path('total-deces', views.total_deces, name='total_deces'),
    path('total-deces-enfant', views.total_deces_enfant, name='total_deces_enfant'),
    path('total-accident', views.total_accident, name='total_accident'),
    path('total-accident-enfant', views.total_accident_enfant, name='total_accident_enfant'),

    # Url des bouttons Coopérative et groupement
    path('liste-secteur-activite', views.liste_secteur_activite, name='liste_secteur_activite'),
    path('liste-membre', views.liste_membre, name='liste_membre'),

]

localisation/urls.py
from django.urls import path
from . import views

app_name = 'localisation'
urlpatterns = [
    path('', views.localisation, name = 'localisation'),

    # Url du district
    path('ajouter-district', views.ajouter_district, name = 'ajouter_district'),
    path('modifier-district', views.modifier_district, name = 'modifier_district'),
    path('supprimer-district/<str:id>', views.supprimer_district, name = 'supprimer_district'),

    # Url de la région
    path('ajouter-region', views.ajouter_region, name = 'ajouter_region'),
    path('modifier-region', views.modifier_region, name = 'modifier_region'),
    path('supprimer-region/<str:id>', views.supprimer_region, name = 'supprimer_region'),
    path('details-region', views.details_region, name = 'details_region'),

    # Url de la département
    path('ajouter-departement', views.ajouter_departement, name = 'ajouter_departement'),
    path('modifier-departement', views.modifier_departement, name = 'modifier_departement'),
    path('supprimer-departement/<str:id>', views.supprimer_departement, name = 'supprimer_departement'),

    # Url de la ville
    path('ajouter-ville', views.ajouter_ville, name = 'ajouter_ville'),
    path('modifier-ville', views.modifier_ville, name = 'modifier_ville'),
    path('supprimer-ville/<str:id>', views.supprimer_ville, name = 'supprimer_ville'),
    path('details-departement', views.details_departement, name = 'details_departement'),

    # Url de la Commune
    path('ajouter-commune', views.ajouter_commune, name = 'ajouter_commune'),
    path('modifier-commune', views.modifier_commune, name = 'modifier_commune'),
    path('supprimer-commune/<str:id>', views.supprimer_commune, name = 'supprimer_commune'),
    path('details-ville', views.details_ville, name = 'details_ville'),

    # Url du Quartier
    path('ajouter-quartier', views.ajouter_quartier, name = 'ajouter_quartier'),
    path('modifier-quartier', views.modifier_quartier, name = 'modifier_quartier'),
    path('supprimer-quartier/<str:id>', views.supprimer_quartier, name = 'supprimer_quartier'),
    path('details-commune', views.details_commune, name = 'details_commune'),

    # Url du Marché
    path('ajouter-marche', views.ajouter_marche, name='ajouter_marche'),
    path('modifier-marche', views.modifier_marche, name='modifier_marche'),
    path('supprimer-marche/<str:id>', views.supprimer_marche, name='supprimer_marche'),
    path('details-quartier', views.details_quartier, name='details_quartier'),
    path('details-marche', views.details_marche, name='details_marche'),
]

presentation/urls.py
from django.urls import path
from . import views

app_name = 'presentation'
urlpatterns = [

    # Url du Secteur Agricole
    path('index/', views.index, name='index'),
    path('ajouter-secteuragricole/', views.ajouter_secteuragricole, name='ajouter_secteuragricole'),
    path('modifier-secteuragricole/<str:id>', views.modifier_secteuragricole, name='modifier_secteuragricole'),
    path('supprimer-secteuragricole/<str:id>', views.supprimer_secteuragricole, name='supprimer_secteuragricole'),
    path('details-secteuragricole/<str:id>', views.detail_secteuragricole, name='detail_secteuragricole'),
    path('details-niveauscolaire/', views.details_niveauscolaire, name='details_niveauscolaire'),
    path('ajouter-secteur-membre', views.ajouter_secteur_membre, name='ajouter_secteur_membre'),
    path('supprimer-secteur-membre', views.supprimer_secteur_membre, name='supprimer_secteur_membre'),
    path('ajouter-document-membre', views.ajouter_document_membre, name='ajouter_document_membre'),
    path('supprimer-document-membre', views.supprimer_document_membre, name='supprimer_document_membre'),
    path('supprimer-parent-membre', views.supprimer_parent_membre, name='supprimer_parent_membre'),
    path('ajouter-parent-membre', views.ajouter_parent_membre, name='ajouter_parent_membre'),
    path('retour-liste-membre/<str:id>', views.retour_liste_membre, name='retour_liste_membre'),
    path('ajouter-etatsante-membre', views.ajouter_etatsante_membre, name='ajouter_etatsante_membre'),
    path('supprimer-etatsante-membre', views.supprimer_etatsante_membre, name='supprimer_etatsante_membre'),
    path('detail-parent-secteuragricole/<str:id>/<str:id_retour>', views.detail_parent_secteuragricole, name='detail_parent_secteuragricole'),
    path('ajouter-etatsante-parent', views.ajouter_etatsante_parent, name='ajouter_etatsante_parent'),
    path('supprimer-etatsante-parent', views.supprimer_etatsante_parent, name='supprimer_etatsante_parent'),
    path('imprimer-secteuragricole/<str:id>', views.imprimer_secteuragricole, name='imprimer_secteuragricole'),

    # Url du Secteur Femme Active
    path('ajouter-secteurfemmeactive/', views.ajouter_secteurfemmeactive, name='ajouter_secteurfemmeactive'),
    path('modifier-secteurfemmeactive/<str:id>', views.modifier_secteurfemmeactive, name='modifier_secteurfemmeactive'),
    path('supprimer-secteurfemmeactive/<str:id>', views.supprimer_secteurfemmeactive, name='supprimer_secteurfemmeactive'),
    path('details-secteurfemmeactive/<str:id>', views.detail_secteurfemmeactive, name='detail_secteurfemmeactive'),
    path('imprimer-secteurfemmeactive/<str:id>', views.imprimer_secteurfemmeactive, name='imprimer_secteurfemmeactive'),


]

projet/urls.py
"""projet URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler400, handler403
from django.conf.urls.static import static

# Configuration des erreurs
handler404 = 'utilisateur.views.handler404'
handler500 = 'utilisateur.views.handler500'
handler400 = 'utilisateur.views.handler400'
handler403 = 'utilisateur.views.handler403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('localisation/', include('localisation.urls')),
    path('etatcivil/', include('etatcivil.urls')),
    path('vieprofessionnelle/', include('vieprofessionnelle.urls')),
    path('presentation/', include('presentation.urls')),
    path('etat/', include('etat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilisateur/urls.py
from django.urls import path
from . import views

app_name = 'utilisateur'
urlpatterns = [
    path('', views.connexion, name = 'connexion'),
    path('inscription/<int:ajouter_utilisateur>', views.inscription, name = 'inscription'),
    path('deconnexion/', views.deconnexion, name = 'deconnexion'),

    path('utilisateur/', views.utilisateur, name = 'utilisateur'),
    path('infos-utilisateur/<int:id>', views.detail_utilisateur, name = 'detail_utilisateur'),
    path('modifier-utilisateur/<int:id>', views.modifier_utilisateur, name = 'modifier_utilisateur'),
    path('supprimer-utilisateur/<int:id>', views.supprimer_utilisateur, name = 'supprimer_utilisateur'),
    path('supprimer-groupe-utilisateur/<int:id>', views.supprimer_groupe_utilisateur, name = 'supprimer_groupe_utilisateur'),


    path('groupe/', views.groupe, name = 'groupe'),
    path('ajouter-groupe/', views.ajouter_groupe, name = 'ajouter_groupe'),
    path('infos-groupe/<int:id>', views.detail_groupe, name = 'detail_groupe'),
    path('modifier-groupe/<int:id>', views.modifier_groupe, name = 'modifier_groupe'),
    path('supprimer-groupe/<int:id>', views.supprimer_groupe, name = 'supprimer_groupe'),
    path('supprimer-utilisateur-groupe/<int:id>', views.supprimer_utilisateur_groupe, name = 'supprimer_utilisateur_groupe'),

    #path('index/', views.index, name = 'index'),
    path('motdepasse/<str:id>', views.motdepasse, name = 'motdepasse'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo_chlohe.ico' %}" />

    <!-- BOOTSTRAP LIEN CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- DATATABLES LIEN CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.6.0/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.css"/>

    <!-- CSS DU PROJET -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}" />

    <title>{% block titre %}Accueil-IRIS{% endblock %}</title>
</head>
<body>
  <div id ="page">

      {% block nas %}
      <div id ="nav">
        {% include 'nav.html' %}
      </div>
      {% endblock %}

    <div id ="contenu" class="container-fluid">
      {% block contenu %}
      {% endblock %}
    </div>

    <div id ="pied_page">
      {% block pied_page %}
        <div class="row" style="margin: 0px;">
            <div class="col-md-6 offset-md-3">
                <p class="text-center">
                    {% now "Y" as annee %}
                    {% if annee == "2022" %}
                    &copy copyright {{annee}} - Tous droits réservés CHLOHE SAS.
                    {% else %}
                    &copy copyright 2022-{{annee}} - Tous droits réservés CHLOHE SAS.
                    {% endif %}
                </p>
            </div>
        </div>
      {% endblock %}
    </div>

  </div>

  <!-- BOOTSTRAP LIEN JAVASCRIPT-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/6b64521285.js" crossorigin="anonymous"></script>

  <!-- DATATABLES-->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.6.0/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.js"></script>

  <!--Recherche avancée des colonnes du tableau -->
  <script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.2.4/js/dataTables.fixedHeader.min.js"></script>

  <!--Popup de notification swal -->
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <!--Imprimer avec printThis -->
  <script src="{% static 'js/printThis.js' %}"></script>

  {% block javascript %}
  {% endblock javascript %}

</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'presentation:index' %}"><i class="fas fa-eye"></i> IRIS</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsNavbar">
    <ul class="navbar-nav">
      {% if not user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilisateur:connexion' %}">Connexion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilisateur:inscription' 0 %}">S'inscrire</a>
      </li>
      {% else %}
      <!-- Menu déroulant -->
      <li class="nav-item dropdown" style="position: relative; z-index:100">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          {{user.get_username}}
        </a>
        <div class="dropdown-menu" style="position: absolute; left:-100px;">
          <a class="dropdown-item" href="{% url 'utilisateur:motdepasse' user.id %}"><i class="fa fa-user-secret"></i> Mot de passe</a>
          {% if 'auht.add_user' in perms %}
          <a class="dropdown-item" href="{% url 'utilisateur:utilisateur' %}"><i class="fa fa-user"></i> Utilisateurs</a>
          <a class="dropdown-item" href="{% url 'utilisateur:groupe' %}"><i class="fa fa-group"></i> Groupes</a>
          <a class="dropdown-item" href="{% url 'localisation:localisation' %}"><i class="fa fa-wrench"></i> Paramètres</a>
          {% endif %}
          <a class="dropdown-item text-danger" href="{% url 'utilisateur:deconnexion' %}"><i class="fa fa-sign-out"></i> Déconnexion</a>
        </div>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/toast.html
<!-- Toast -->
<div aria-live="polite" aria-atomic="true"
     style="position: fixed; min-height: 200px; top: 0; right: 0;" >
    <div class="toast fade" data-delay="500" data-autohide="true" data-animation="true" id="mytoast_success">
        <div class="toast-header text-black" style="background: rgba(0,255,0,0.8);">
            <span class="mr-auto"><i class="fas fa-info-circle"></i> Information</span>
            <button id="btn_ferme_toast_success" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Enregistrement réussi.
        </div>
    </div>
</div>
<!-- -->

<!-- Toast -->
<div aria-live="polite" aria-atomic="true"
     style="position: fixed; min-height: 200px; top: 0; right: 0;" >
    <div class="toast fade" data-delay="500" data-autohide="true" data-animation="true" id="mytoast_modification">
        <div class="toast-header text-black" style="background: rgba(0,255,0,0.8);">
            <span class="mr-auto"><i class="fas fa-info-circle"></i> Information</span>
            <button id="btn_ferme_toast_modification" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Modification réussie.
        </div>
    </div>
</div>
<!-- -->

<!-- Toast -->
<div aria-live="polite" aria-atomic="true"
     style="position: fixed; min-height: 200px; top: 0; right: 0;" >
    <div class="toast fade" data-delay="500" data-autohide="true" data-animation="true" id="mytoast_suppression">
        <div class="toast-header text-black" style="background: rgba(0,255,0,0.8);">
            <span class="mr-auto"><i class="fas fa-info-circle"></i> Information</span>
            <button id="btn_ferme_toast_suppression" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Suppression réussie.
        </div>
    </div>
</div>
<!-- -->